name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: j178/prek-action@v2
